import uuid
from datetime import datetime

from pgvector.sqlalchemy import Vector
from sqlalchemy import BigInteger, DateTime, Float, ForeignKey, Index, Integer, String, Text, UniqueConstraint, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.config import settings
from app.core.database import Base

# Document processing status flow:
# uploading → splitting → glm_ocr → section_mapping → captioning → embedding → ready
# Any stage can transition to → failed.
# `section_mapping` is the offline enrichment pass that builds the
# book → topic → subtopic → headline tree (see app.tasks.section_mapping).
DOCUMENT_STATUSES = (
    "uploading",
    "splitting",
    "glm_ocr",
    "section_mapping",
    "captioning",
    "embedding",
    "ready",
    "failed",
)

DOCUMENT_ACTIVE_STAGES = (
    "splitting",
    "glm_ocr",
    "section_mapping",
    "captioning",
    "embedding",
)

# Section hierarchy kinds. A book has Topics → Subtopics → Headlines.
# Only Headlines carry the full enrichment payload (concepts, equations,
# outcomes). Topics and Subtopics carry rollups of their children.
SECTION_KINDS = ("topic", "subtopic", "headline")


class Document(Base):
    __tablename__ = "documents"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    group_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("groups.id", ondelete="CASCADE"), nullable=False, index=True
    )
    filename: Mapped[str] = mapped_column(String(500), nullable=False)
    file_url: Mapped[str] = mapped_column(String(1000), nullable=False)
    file_size_bytes: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    page_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="uploading")
    current_stage: Mapped[str | None] = mapped_column(String(20), nullable=True)
    progress_current: Mapped[int | None] = mapped_column(Integer, nullable=True)
    progress_total: Mapped[int | None] = mapped_column(Integer, nullable=True)
    error_detail: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Cached printed-page-number to internal-page-index offset (LLM-
    # resolved on first viewer open). NULL = not yet computed.
    printed_page_offset: Mapped[int | None] = mapped_column(Integer, nullable=True)
    uploaded_by: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id"), nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    # Relationships
    group = relationship("Group", back_populates="documents")
    pages = relationship("Page", back_populates="document", cascade="all, delete-orphan")
    chunks = relationship("Chunk", back_populates="document", cascade="all, delete-orphan")
    sections = relationship(
        "DocumentSection",
        back_populates="document",
        cascade="all, delete-orphan",
        foreign_keys="DocumentSection.document_id",
    )


class Page(Base):
    __tablename__ = "pages"
    __table_args__ = (
        UniqueConstraint("document_id", "page_number", name="uq_pages_document_page_number"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    document_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("documents.id", ondelete="CASCADE"), nullable=False, index=True
    )
    page_number: Mapped[int] = mapped_column(Integer, nullable=False)
    image_url: Mapped[str] = mapped_column(String(1000), nullable=False)
    markdown: Mapped[str | None] = mapped_column(Text, nullable=True)
    ocr_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    ocr_confidence: Mapped[float | None] = mapped_column(Float, nullable=True)
    regions: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    # Relationships
    document = relationship("Document", back_populates="pages")
    chunks = relationship("Chunk", back_populates="page", cascade="all, delete-orphan")


class DocumentSection(Base):
    """One node in the book → topic → subtopic → headline tree.

    Generated by the offline section_mapping stage during ingestion.
    Headlines carry the full enrichment payload (summary, concepts
    introduced/assumed, key equations, outcomes, difficulty, type,
    hooks) inside `content_json`. Topics and subtopics carry rolled-up
    summaries of their children's payloads.

    Hierarchy is self-referential via `parent_id`. Root nodes (topics)
    have `parent_id IS NULL` and `kind = 'topic'`. Ordering within a
    parent is by `ordinal` ascending.

    Embeddings live in a separate `DocumentSectionEmbedding` table —
    same pattern as ChunkEmbedding — so the main row stays light and
    embedding generation can run as a separate step after enrichment.
    """

    __tablename__ = "document_sections"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    document_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("documents.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    parent_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("document_sections.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    # 'topic' | 'subtopic' | 'headline'. See SECTION_KINDS.
    kind: Mapped[str] = mapped_column(String(20), nullable=False)
    title: Mapped[str] = mapped_column(Text, nullable=False)
    # Internal (1-indexed) page range this section covers. End is
    # inclusive. For Topic / Subtopic these are derived from the
    # union of child headline ranges.
    page_start: Mapped[int] = mapped_column(Integer, nullable=False)
    page_end: Mapped[int] = mapped_column(Integer, nullable=False)
    # Order within parent, 0-indexed. Lets us preserve book reading
    # order without relying on `id` or `created_at` ties.
    ordinal: Mapped[int] = mapped_column(Integer, nullable=False)
    # Enrichment payload — schema described in app.tasks.section_mapping.
    # Null until the section_mapping stage has run for this node.
    content_json: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    # Relationships
    document = relationship(
        "Document", back_populates="sections", foreign_keys=[document_id]
    )
    parent = relationship(
        "DocumentSection",
        remote_side="DocumentSection.id",
        back_populates="children",
    )
    children = relationship(
        "DocumentSection",
        back_populates="parent",
        cascade="all, delete-orphan",
        order_by="DocumentSection.ordinal",
    )
    embedding = relationship(
        "DocumentSectionEmbedding",
        back_populates="section",
        uselist=False,
        cascade="all, delete-orphan",
    )


class DocumentSectionEmbedding(Base):
    """Semantic-search embedding for a DocumentSection.

    Embedded over the section's summary + concepts_introduced names +
    outcomes — i.e. *what the section teaches*, not the raw page text.
    Used by the learn-mode path generator to match a user's free-text
    goal against the most relevant headlines.
    """

    __tablename__ = "document_section_embeddings"

    section_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("document_sections.id", ondelete="CASCADE"),
        primary_key=True,
    )
    embedding = mapped_column(Vector(settings.embedding_dimensions), nullable=False)

    # Relationships
    section = relationship("DocumentSection", back_populates="embedding")


# IVFFlat index for fast approximate nearest neighbor search over
# section summaries. Same pattern as chunk_embeddings.
Index(
    "idx_document_section_embeddings_ivfflat",
    DocumentSectionEmbedding.embedding,
    postgresql_using="ivfflat",
    postgresql_with={"lists": 100},
    postgresql_ops={"embedding": "vector_cosine_ops"},
)
