"""add suggested_questions column to messages

Stores up to ~5 follow-up question strings (in the user's language)
generated by the answer model. The frontend renders them as clickable
chips below the assistant message, turning Library mode into a guided
learning experience rather than a one-shot Q&A endpoint.

Nullable so existing messages remain valid; new assistant messages
populate the field on creation.

Revision ID: 020_msg_suggested_questions
Revises: 019_chunk_anchors_column
Create Date: 2026-05-05
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB

revision: str = "020_msg_suggested_questions"
down_revision: Union[str, None] = "019_chunk_anchors_column"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("messages", sa.Column("suggested_questions", JSONB, nullable=True))


def downgrade() -> None:
    op.drop_column("messages", "suggested_questions")
